// vm-tutorial - Virtual machine tutorial targeting CHIP-8
//
// Written in 2021 by Michael Rodriguez aka kaichiuchu <mike@kaichiuchu.dev>
//
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication along
// with this software. If not, see
// <http://creativecommons.org/publicdomain/zero/1.0/>.

#pragma once

#include <QMainWindow>

#include "../types.h"
#include "core/impl.h"
#include "models/debugger_disasm.h"
#include "models/debugger_registers.h"
#include "models/debugger_stack.h"
#include "ui_debugger_window.h"

/// This class handles the logic of user actions that take place in the
/// debugger window.
///
/// The debugger window contains various controls used to inspect, but not
/// modify the contents of the virtual machine.
class DebuggerWindowController : public QMainWindow {
  Q_OBJECT

 public:
  /// Constructs the debugger window.
  ///
  /// \param vm_instance The virtual machine instance.
  explicit DebuggerWindowController(chip8::VMInstance& vm_instance) noexcept;

  /// Notifies the user that a breakpoint has been reached, and adjusts the view
  /// accordingly.
  ///
  /// \param address The address of the breakpoint.
  void NotifyBreakpointHit(uint_fast16_t address) noexcept;

  /// Enables or disables the debugger controls.
  ///
  /// The debugger controls should be disabled when the emulator is running, and
  /// enabled when it is not.
  ///
  /// \param enabled \p true if the debugger controls should be enabled, or \p
  /// false otherwise.
  void EnableControls(const bool enabled) noexcept;

 private:
  /// Attempts to scroll to an address on the disassembler view.
  ///
  /// \param address The address to scroll to.
  ///
  /// \returns \p true if the address was valid and the view was scrolled, or \p
  /// false otherwise.
  auto ScrollToAddress(uint_fast16_t address) noexcept -> bool;

  /// Notifies the user that the value provided in the address input dialog
  /// could not be converted due to an internal Qt fault.
  ///
  /// \param address_text The address the user entered.
  void NotifyValueConversionError(const QString& address_text) noexcept;

  /// Notifies the user that the value provided in the address input dialog is
  /// not a valid address.
  ///
  /// \param address The address the user entered.
  void NotifyInvalidJumpAddress(uint_fast16_t address) noexcept;

  /// Connects signals from various widgets to slots.
  void ConnectSignalsToSlots() noexcept;

  /// Configures the debugger based on the current application settings.
  void SetupFromAppSettings() noexcept;

  /// The widget view as generated by the User Interface Compiler (UIC).
  Ui::DebuggerWindow view_;

  /// The model which handles the CHIP-8 disassembly.
  DebuggerDisasmModel* disasm_model_;

  /// The model which handles the CHIP-8 register data.
  DebuggerRegistersModel* registers_model_;

  /// The model which handles the CHIP-8 stack data.
  DebuggerStackModel* stack_model_;

  /// The CHIP-8 virtual machine instance.
  chip8::VMInstance& vm_instance_;

 signals:
  /// Emitted when the Pause/Continue button has been pressed.
  void ToggleRunState();
};
