// vm-tutorial - Virtual machine tutorial targeting CHIP-8
//
// Written in 2021 by Michael Rodriguez aka kaichiuchu <mike@kaichiuchu.dev>
//
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication along
// with this software. If not, see
// <http://creativecommons.org/publicdomain/zero/1.0/>.

#pragma once

#include <QWidget>

#include "ui_general_settings.h"

/// This class handles the logic of user actions that take place in the general
/// settings widget. The general settings widget handles, so far, the default
/// location where to look for CHIP-8 programs.
class GeneralSettingsController : public QWidget {
  Q_OBJECT

 public:
  /// Constructs the general settings controller.
  ///
  /// \param parent_widget The parent object of which this class is a child of
  /// it.
  explicit GeneralSettingsController(QWidget* parent_widget) noexcept;

 private:
  /// Connects various signals from the interface to slots.
  void ConnectSignalsToSlots() noexcept;

  /// Populates the widget with the current general settings.
  void PopulateDataFromAppSettings() noexcept;

  /// The widget view as generated by the User Interface Compiler (UIC).
  Ui::GeneralSettings view_;
};
