// vm-tutorial - Virtual machine tutorial targeting CHIP-8
//
// Written in 2021 by Michael Rodriguez aka kaichiuchu <mike@kaichiuchu.dev>
//
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication along
// with this software. If not, see
// <http://creativecommons.org/publicdomain/zero/1.0/>.

#pragma once

#include <QWidget>

#include "ui_graphics_settings.h"

/// This class handles the logic of user actions that take place in the graphics
/// settings widget.
///
/// The graphics settings only, so far, handle the state of bilinear filtering.
class GraphicsSettingsController : public QWidget {
  Q_OBJECT

 public:
  /// Constructs the graphics settings controller.
  ///
  /// \param parent_widget The parent object of which this class is a child of
  /// it.
  explicit GraphicsSettingsController(QWidget* parent_widget) noexcept;

 private:
  /// Connects signals from various widgets to slots.
  void ConnectSignalsToSlots() noexcept;

  /// Populates the graphics settings with the current graphics settings.
  void PopulateDataFromAppSettings() noexcept;

  /// The widget view as generated by the User Interface Compiler (UIC).
  Ui::GraphicsSettings view_;

 signals:
  /// Emitted when the state of bilinear filtering has changed.
  ///
  /// \param enabled \p true if bilinear filtering is now enabled, or \p false
  /// otherwise.
  void BilinearFilteringStateChanged(bool enabled);
};
