// vm-tutorial - Virtual machine tutorial targeting CHIP-8
//
// Written in 2021 by Michael Rodriguez aka kaichiuchu <mike@kaichiuchu.dev>
//
// To the extent possible under law, the author(s) have dedicated all copyright
// and related and neighboring rights to this software to the public domain
// worldwide. This software is distributed without any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication along
// with this software. If not, see
// <http://creativecommons.org/publicdomain/zero/1.0/>.

#pragma once

#include <QWidget>

#include "ui_machine_settings.h"

/// This class handles the logic of user actions that take place in the machine
/// settings widget.
///
/// The machine settings widget allows the user to change the timing of the
/// virtual machine.
class MachineSettingsController : public QWidget {
  Q_OBJECT

 public:
  /// Constructs the machine settings controller.
  ///
  /// \param parent_widget The parent object of which this class is a child of
  /// it.
  explicit MachineSettingsController(QWidget* parent_widget) noexcept;

 private:
  /// Connects signals from various widgets to slots.
  void ConnectSignalsToSlots() noexcept;

  /// Populates the machine settings widget with the current machine settings.
  void PopulateDataFromAppSettings() noexcept;

  /// The widget view as generated by the User Interface Compiler (UIC).
  Ui::MachineSettings view_;

 signals:
  /// Emitted when the user has requested to change the number of instructions
  /// per second.
  void MachineInstructionsPerSecondChanged(int value);

  /// Emitted when the user has requested to change the number of frames per
  /// second.
  void MachineFrameRateChanged(double value);
};
